In [12]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

from data_access import init

In [14]:
data = init('scratchandpatch')

In [15]:
data_type = 'snapshot'
current_asat = '2023-09-30'

In [16]:
data.get_top_claims(current_asat)

   POLICY_REF    CLAIM_REF   YOA  TOTAL_INC        MAJOR_LOB
0  SNP0030520  26243630465  2020  22,136.53  Scratch & Patch
1  SNP0030123  66450656859  2020  18,540.00  Scratch & Patch
2  SNP0034739  90445899045  2021  13,161.46  Scratch & Patch
3  SNP0017748     PC009566  2020  12,399.49  Scratch & Patch
4  SAP0044560      2544750  2022  11,536.00  Scratch & Patch
5  SNP0034240  88624697028  2020   9,202.00  Scratch & Patch
6  SNP0008298  98519382047  2018   9,189.60  Scratch & Patch
7  SNP0026631     PC010175  2020   8,584.36  Scratch & Patch
8  SAP0049484      2572848  2022   8,000.00  Scratch & Patch
9  SNP0038965  69256243628  2021   8,000.00  Scratch & Patch

In [17]:
previous_asat = '2023-08-31'
data.get_top_claims(previous_asat)

   POLICY_REF    CLAIM_REF   YOA  TOTAL_INC        MAJOR_LOB
0  SNP0030520  26243630465  2020  22,136.53  Scratch & Patch
1  SNP0030123  66450656859  2020  18,540.00  Scratch & Patch
2  SNP0034739  90445899045  2021  13,161.46  Scratch & Patch
3  SNP0017748     PC009566  2020  12,399.49  Scratch & Patch
4  SAP0044560      2544750  2022  11,536.00  Scratch & Patch
5  SNP0034240  88624697028  2020   9,202.00  Scratch & Patch
6  SNP0008298  98519382047  2018   9,189.60  Scratch & Patch
7  SNP0026631     PC010175  2020   8,584.36  Scratch & Patch
8  SAP0049748      2630014  2022   8,189.20  Scratch & Patch
9  SNP0018347  66341067088  2021   8,000.00  Scratch & Patch

In [18]:
data.get_biggest_movement(current_asat, previous_asat)

,POLICY_REF,CLAIM_REF,YOA,MAJOR_LOB,TOTAL_INC_CURRENT,TOTAL_INC_PREVIOUS,INC_MOVEMENT,ABS_MOVEMENT
0,SAP0051261,2655475,2022,Scratch & Patch,"1,777.51","6,998.66","-5,221.15","5,221.15"
1,SAP0060402,2657066,2023,Scratch & Patch,0.00,"4,346.99","-4,346.99","4,346.99"
2,SAP0062554,2636229,2023,Scratch & Patch,"1,738.30","6,077.45","-4,339.15","4,339.15"
3,SAP0050808,2651577,2022,Scratch & Patch,0.00,"4,000.00","-4,000.00","4,000.00"
4,SAP0060209,2649600,2023,Scratch & Patch,"3,909.86",0.00,"3,909.86","3,909.86"
5,SAP0048813,2471609,2022,Scratch & Patch,"4,186.11",501.00,"3,685.11","3,685.11"
6,SAP0061439,2661558,2023,Scratch & Patch,"2,000.00","5,010.72","-3,010.72","3,010.72"
7,SAP0048924,2646034,2022,Scratch & Patch,0.00,"2,876.61","-2,876.61","2,876.61"
8,SAP0053883,2633159,2022,Scratch & Patch,"2,958.16",148.63,"2,809.53","2,809.53"
9,SAP0053370,2649176,2022,Scratch & Patch,0.00,"2,614.29","-2,614.29","2,614.29"

In [19]:
data.get_biggest_new_claims(current_asat, previous_asat)

   POLICY_REF CLAIM_REF        MAJOR_LOB   YOA  TOTAL_INC
0  SAP0054056   2670714  Scratch & Patch  2022   7,700.00
1  SAP0065260   2678678  Scratch & Patch  2023   7,406.93
2  SAP0060651   2671392  Scratch & Patch  2023   7,301.33
3  SAP0065820   2677141  Scratch & Patch  2023   7,063.28
4  SAP0065820   2674200  Scratch & Patch  2023   6,024.19
5  SAP0049484   2666938  Scratch & Patch  2022   4,821.18
6  SAP0066083   2678576  Scratch & Patch  2023   4,425.77
7  SAP0053389   2682917  Scratch & Patch  2022   4,393.34
8  SAP0066853   2677252  Scratch & Patch  2023   4,000.00
9  SAP0053866   2676495  Scratch & Patch  2022   3,739.06

In [20]:
trans_data = init('freedom_health')
current_asat='2024-09-30'
previous_asat='2024-08-31'

In [21]:
trans_data.get_top_ftl_claims(current_asat)

    POLICY_REF CLAIM_REF   YOA      MAJOR_LOB      TOT_INC
0   GRQ03746-1     33127  2022  AllianzFrance 2,874,888.69
1   GRQ03746-1     33127  2023  AllianzFrance 1,512,458.73
2   GRQ04126-1     31394  2022  AllianzFrance 1,168,214.70
3   GRQ03662-1     33867  2022  AllianzFrance   749,758.08
4   GRQ04588-1     28570  2022  AllianzFrance   471,923.70
5   GRQ04415-1     30986  2022  AllianzFrance   429,013.95
6   GRQ05484-1     32252  2022  AllianzFrance   350,519.64
7   GRQ03647-1     28031  2022  AllianzFrance   317,935.26
8   GRQ02882-1     29452  2022  AllianzFrance   279,728.52
9   GRQ02840-1     40962  2023  AllianzFrance   229,885.44
10  GIZ08516-2     43317  2023      AllianzUK   686,317.20
11  GIZ09136-1     24678  2021      AllianzUK   617,409.93
12  GIZ09136-1     24678  2022      AllianzUK   612,867.95
13  GIZ05494-1     17991  2023      AllianzUK   589,953.01
14  GIZ09136-1     24678  2023      AllianzUK   580,685.58
15  GIZ05494-1     17991  2022      AllianzUK   553,522.22
16  GIZ01841-1     15863  2022      AllianzUK   542,077.97
17  GIZ07516-1     20140  2021      AllianzUK   434,265.71
18  GIZ05494-1     17991  2021      AllianzUK   387,121.48
19  GIZ08043-2     45266  2023      AllianzUK   383,933.87

In [22]:
trans_data.get_biggest_ftl_movement(current_asat, previous_asat)

,POLICY_REF,CLAIM_REF,YOA,MAJOR_LOB,PREVIOUS_TOTAL,CURRENT_TOTAL,MOVEMENT,ABS_MOVEMENT
0,GRQ06471-1,43609,2023,AllianzFrance,"53,350.33","65,845.86","12,495.53","12,495.53"
1,GRQ03354-1,24884,2023,AllianzFrance,"5,439.77","14,132.32","8,692.55","8,692.55"
2,GRQ02796-1,41698,2023,AllianzFrance,"37,461.53","44,105.54","6,644.01","6,644.01"
3,GRQ04050-1,45984,2024,AllianzFrance,"18,851.18","25,154.22","6,303.04","6,303.04"
4,GRQ02783-1,43242,2024,AllianzFrance,"12,509.19","16,350.03","3,840.84","3,840.84"
5,GRQ05377-1,45402,2023,AllianzFrance,"21,034.32","23,496.94","2,462.62","2,462.62"
6,GRQ04802-1,45076,2023,AllianzFrance,0.00,"2,413.77","2,413.77","2,413.77"
7,GRQ02946-1,48422,2024,AllianzFrance,"5,233.88","7,502.08","2,268.20","2,268.20"
8,GRQ04264-1,46421,2024,AllianzFrance,246.02,"2,416.28","2,170.26","2,170.26"
9,GRQ03618-1,24609,2024,AllianzFrance,972.76,"2,435.21","1,462.45","1,462.45"
10,GIZ01841-1,15863,2022,AllianzUK,"217,166.39","162,455.79","-54,710.60","54,710.60"
11,GIZ05494-1,17991,2024,AllianzUK,"58,973.44","105,647.69","46,674.25","46,674.25"
12,GIZ09136-1,24678,2024,AllianzUK,"43,881.37","81,976.82","38,095.45","38,095.45"
13,GIZ04022-1,26847,2022,AllianzUK,"110,581.17","83,316.01","-27,265.16","27,265.16"
14,GIZ08198-1,25720,2021,AllianzUK,"42,537.59","20,492.73","-22,044.86","22,044.86"
15,GIZ11005-1,42929,2024,AllianzUK,"101,542.78","122,198.68","20,655.90","20,655.90"
16,GIZ07882-1,24798,2021,AllianzUK,"121,782.81","104,609.80","-17,173.01","17,173.01"
17,GCZ00652-1-1,40044,2024,AllianzUK,"70,602.64","86,734.64","16,132.00","16,132.00"
18,GIZ01841-1,15863,2021,AllianzUK,"53,811.46","38,370.52","-15,440.94","15,440.94"
19,GIZ11644-1,44410,2023,AllianzUK,"1,917.31","16,504.78","14,587.47","14,587.47"

In [24]:
trans_data.top_new_ftl_claims(current_asat, previous_asat)

   CLAIM_REF     POLICY_REF   YOA      MAJOR_LOB  TOTAL_INC
0      47749     GRQ06132-1  2024  AllianzFrance  27,065.40
1      49972     GRQ03137-1  2023  AllianzFrance   7,824.56
2      49182     GRQ04037-1  2024  AllianzFrance   7,260.49
3      49778     GRQ04215-1  2024  AllianzFrance   6,368.80
4      48435     GRQ03948-1  2024  AllianzFrance   3,413.34
5      41698     GRQ02796-1  2024  AllianzFrance   3,183.43
6      49953     GRQ03457-1  2023  AllianzFrance   3,003.97
7      49805     GRQ03915-1  2024  AllianzFrance   2,955.10
8      49934     GRQ02867-1  2024  AllianzFrance   2,954.42
9      49562     GRQ04624-1  2023  AllianzFrance   1,487.60
10     43386     GIZ10916-1  2024      AllianzUK  21,780.50
11     27512     GIZ08524-1  2023      AllianzUK  13,927.84
12     29136     GIZ07908-1  2024      AllianzUK  10,887.19
13     49276     GIZ12138-1  2024      AllianzUK   9,785.39
14     49203     GIZ12360-1  2024      AllianzUK   5,897.90
15     49498  GCZ00724-89-1  2024      AllianzUK   4,623.78
16     36976     GIZ11392-1  2024      AllianzUK   4,198.40
17     48118     GIZ05739-1  2024      AllianzUK   4,138.18
18     42528     GIZ08388-1  2023      AllianzUK   3,826.75
19     49321     GIZ02986-1  2023      AllianzUK   3,786.66